### ISSUE TITLE
How to assemble an 80960KB program from a disassembly?

### ISSUE THREAD

**Issue by biggestsonicfan** [SailorSat/OpenDaytona#1]
I am assuming Sega originally used a tool provided by Intel called [CTOOLS](https://web.archive.org/web/20040711161357/http://developer.intel.com/design/i960/patches/rBinary.htm). However, a disassembly might be able to be built with GNU960. The last supported GCC for the i960 architecture was [3.4.6](https://gcc.gnu.org/gcc-3.4/changes.html) (See "Obsolete Systems"). However, this is a disassembly, not source code, so we would need binutils, and the last build that supported the i960 architecture that I could successfully compile using cygwin was binutils 2.16.1a, both ELF and COFF formats.

So what would be required to build a disassembly of an i960 program? If deemed too difficult, however, is this repository purely going to be for research purposes?

**Comment by SailorSat** [comment]
To be honest, I didn't think about that yet. For the time being I'm just document that assembly.

**Comment by biggestsonicfan** [comment]
Alright, but for future reference, I unearthed an 80960 Windows-compatible assembler from CTOOLS 6.0 [here](https://github.com/cglmrfreeman/i960-CTOOLS-with-NINDY/blob/master/w95-ctools/bin/gas960.exe) with thanks to a professor at the Oregon Institue of Technology. Also if you're interested in turning a disassembly into C code, might I suggest the [ghidra_i960](https://github.com/mumbel/ghidra_i960) project. It's not 100% yet, but I am working with the author to help assist in my own Model2 disassembly of a different game.

**Comment by biggestsonicfan** [comment]
Linux compatible GCC for both [coff](https://archive.org/details/i960-coff-gcc-3.4.6.tar) and [elf](https://archive.org/details/i960-elf-gcc-3.4.6.tar) formats were compiled by @DrItanium. 80690 assembly files can be built from this, however getting a disassembly to a point where it can be built with the tools is a different issue itself. Closing.
